# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'stock_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stock.StockInfo', to_field='name')),
                ('time', models.DateField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.IntegerField()),
                ('open', models.FloatField()),
            ],
            options={
                'db_table': 'history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Realtime',
            fields=[
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stock.StockInfo', to_field='name')),
                ('time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('volume', models.IntegerField()),
            ],
            options={
                'db_table': 'realtime',
                'managed': False,
            },
        ),
    ]
